export const DateCourseQuestion = [
    {
        id: 1,
        filterTitle: '예산 범위',
        title: '오늘 데이트, 얼마나 쓰실 생각이세요?',
        subTitle: '(1인당)',
        keyword: '예산 범위',
        options: ['1만원 이하', '1-2만원', '2-3만원', '3만원 이상'],
        type: 'choice',
    },
    {
        id: 2,
        title: '어디에서 만날까요?',
        subTitle: null,
        keyword: '만날 장소',
        options: null,
        type: 'search',
        filterTitle: '만날 장소',
    },
    {
        id: 3,
        title: '얼마나 함께할 예정인가요?',
        subTitle: '(1개만 선택 가능)',
        keyword: '데이트 시간',
        options: ['1-2시간', '3-4시간', '반나절', '하루 종일'],
        type: 'choice',
        filterTitle: '데이트 시간',
    },
    {
        id: 4,
        title: '어떤 식사를 함께할 계획인가요?',
        subTitle: null,
        keyword: '식사 구성',
        options: ['아침', '점심', '저녁'],
        type: 'choices',
        filterTitle: '식사 구성',
    },
    {
        id: 5,
        title: '어떻게 이동하실 건가요?',
        subTitle: null,
        keyword: '이동 수단',
        options: ['도보', '자차', '대중교통'],
        type: 'choice',
        filterTitle: '',
    },
    {
        id: 6,
        title: '오늘은 어떤 분위기의 데이트를 원하시나요?',
        subTitle: null,
        keyword: '데이트 키워드',
        options: null,
        type: 'keyword',
        filterTitle: '데이트 키워드',
    },
    {
        id: 7,
        title: '데이트 시작 시간을 알려주세요!',
        subTitle: '24:00 기준',
        keyword: null,
        options: null,
        type: 'time',
        filterTitle: '만날 시간',
    },
];
